redis-cluster:
  enabled: false
redis:
  enabled: false
postgresql:
  enabled: false
postgresql-ha:
  enabled: false

persistence:
  enabled: true      

gitea:
  config:
    database:
      DB_TYPE: mysql
      HOST: gitea-mysql.default.svc.cluster.local:3306
      NAME: giteadb
      USER: giteauser
      PASSWD: giteapass
    session:
      PROVIDER: memory
    cache:
      ADAPTER: memory
    queue:
      TYPE: level
